### ISSUE TITLE
Error when trying to remove another user's product.

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/pzserver_app#192]
When trying to remove a product registered by another user, an error appears even when using an official account.

The desired behavior is as follows: regular users only see the opt-out on their own products, while official users are allowed to remove any product.

![image](https://github.com/linea-it/pzserver_app/assets/101944851/83e30b7c-9f72-4511-a400-92632bcb3cdc)

**Comment by gschwend** [comment]
When a user tries to delete another user's data product, please just add a pop-up window with the message: "You can not delete this data product because it belongs to another user."
