### ISSUE TITLE
Reproduce deploy procedure on srvpz-dev following the recording of tutorial meeting

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#290]

**Comment by deborajanini** [comment]
@gschwend qual o size?

**Comment by gschwend** [comment]
@deborajanini @jandsonrj 
FYI movendo para backlog, perdeu prioridade.

**Comment by gschwend** [comment]
passo-a-passo registrado em https://docs.google.com/document/d/10RsgtVgxVIeFJPutEeBZQI0zNwlZ661NhlB-xIwc6qQ/edit?usp=sharing
