### ISSUE TITLE
test TSM front-end 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#292]
Simple test of TSM front-end, without scientific validation.

**October 17th, 2024**
I tested the TSM front-end in the dev environment, using the following parameters:

1. TSM Test - DP02 object vs DP01 truth random sample
2. random truth z / gschwend / 2024-09-12
3. LSST DP0.2
4. threshold distance=1,0; number of neighbors=1; keep the closest only.

The frontend shows the message "Your process has been submited successfully", but no process is triggered in the cluster and no data product is generated in the pz-server dev environment.
We have to wait for Julia and Singulani, who are on vacation, to see what is the problem, so the issue is **blocked**.

**Comment by luigilcsilva** [comment]
Oii, @gschwend e @crisingulani! Depois, quando voltarem, deem uma olhada nisso aqui, por favor.

**Comment by luigilcsilva** [comment]
Fiz o teste do TSM. Tem um notebook bem simples com uma inspeção [aqui](https://pz-server-dev.linea.org.br/product/193_test_tsm). Aparentemente está tudo certo. O histograma de separação tá estranho, mas acho que é por misturar dados reais com dados simulados. Tenho uma sugestão: disponibilizar também o catálogo na estrutura HATS em um .zip. Atualmente vem só um .parquet único. Seria legal ter o output no formato HATS para fazer o plot dos pixels, inspeção dos tamanhos dos arquivos, etc.

Imagino que depois seja implementado o crossmatching com margin_cache também, pois este não teve nenhum duplicate (por não ter margin_cache, imagino).
